# Book settings
title: Python Intensive Course
author: Jorge Huanca Martinez
logo: img/logo.png
copyright: "2023"
exclude_patterns: ["cache"]

# Execution settings
execute:
  execute_notebooks: 'cache'
  cache            : 'cache'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/jorgehmartinez/jb-python-course  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_issues_button    : false
  use_edit_page_button : false

launch_buttons:
  binder             : false
  binderhub          : false
  bunderhub_url      : https://mybinder.org
  jupyterhub         : false
  thebe              : true
  colab              : false
  notebook_interface : classic
  colab_url          : https://colab.research.google.com
    
deploy:
  repository: jorgehmartinez/python_course_book
  remote_branch: gh-pages
  path_to_book: _build/html/